# Generated by Django 3.0.7 on 2020-06-05 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_auto_20200605_0143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mappoint',
            name='lat',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='mappoint',
            name='long',
            field=models.FloatField(),
        ),
    ]
